# .streamlit/secrets.toml
server = "aswweudevasx128.sql.azuresynapse.net"
database = "mazsbxsql"
username = "sqldwqsandbox_mazsbxsql_ro"
password = "oQsiWR0nkE3s1#RZ2N"

# upload config details
op_username = "profit_streamlit"
op_password = "g!xKoEp8&mjWuW1*fyHdYLGrBA7e"